# file: roles/nginx/tasks/main.yml
---
- name: Install epel repo
  yum: name=epel-release state=present
- name: Install nginx
  yum: name=nginx state=present
- name: Deploy the config file
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
- name: update the web files
    copy:
      src: usr/share/www/html/
      dest: /usr/share/www/html/
- name: Start and enable Nginx
  service: name=nginx state=started enabled=yes
  